source("loaddata.R")
d <- loaddata()
png("plot1.png",width=480,height=480)
par(cex = 0.75)
hist(d$Global_active_power,main="Global Active Power",xlab = "Global Active Power (kilowatts)", col = "orangered3")
dev.off()