source("loaddata.R")
d <- loaddata()
png("plot3.png",width=480,height=480)
par(cex = 0.75)
plot(d$DateTime,d$Sub_metering_1,type = "n",xlab = "",ylab = "Energy sub metering")
lines(d$DateTime,d$Sub_metering_1,col="black")
lines(d$DateTime,d$Sub_metering_2,col="red")
lines(d$DateTime,d$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1))
dev.off()